// packages/react-demo/src/App.js
import React from 'react'
// import FlagCanada from '../../flags/src/icons/Canada.jsx'
import { FlagsCanada } from '../../flags/src'
import { CoreArrowCircle } from '../../core/src'

class App extends React.Component {
  render() {
    const { name } = this.props
    return (
      <>
        <h1>
          Hello {name}
        </h1>
        <FlagsCanada variant='rectangle' size='600' rotate='nne'></FlagsCanada>
        <CoreArrowCircle variant='duo' size='600' rotate='nne' strokeWidth='2'></CoreArrowCircle>
      </>
    )
  }
}

export default App

// packages/vue/demo/src/App.vue
<template>
  <div id="app">
    <flags-cuba variant="rectangle" size="200"></flags-cuba>
    <core-arrow-solid variant="path" strokeWidth='4' size='200'></core-arrow-solid>
  </div>
</template>

<script>
import { CoreArrowSolid } from '../../core/src'
import { FlagsCuba } from '../../flags/src'

export default {
  name: 'App',
  components: {
    CoreArrowSolid,
    FlagsCuba
  }
}
</script>
Z
