// packages/react/demo/src/App.js
import React from 'react'
// import FlagCanada from '../../flags/src/icons/Canada.jsx'
import { FlagsCanada } from '../../flags/src'
console.log(FlagsCanada)

class App extends React.Component {
  render() {
    const { name } = this.props
    return (
      <>
        <h1>
          Hello {name}
        </h1>
        <FlagsCanada variant='circle' size='600'></FlagsCanada>
      </>
    )
  }
}

export default App

// packages/vue/demo/src/App.vue
<template>
  <div id="app">
    <core-arrow-solid variant="path"></core-arrow-solid>
    <flags-cuba variant="circle" size="600"></flags-cuba>
  </div>
</template>

<script>
import { CoreArrowSolid } from '../../core/src'
import { FlagsCuba } from '../../flags/src'

export default {
  name: 'App',
  components: {
    CoreArrowSolid,
    FlagsCuba
  }
}
</script>
Z
